ALTER TABLE public.procedure_steps ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now(), ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.procedure_names ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now(), ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.procedure_preset_fields ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now(), ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.surgical_approaches ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now(), ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.team_surgeons ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now(), ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.team_pas ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now(), ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.procedure_reexplorations ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now(), ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.procedure_attachments ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now(), ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.procedures ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.procedure_presets ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

DROP TRIGGER IF EXISTS set_updated_at ON public.procedure_steps;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.procedure_steps FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at ON public.procedure_names;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.procedure_names FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at ON public.procedure_preset_fields;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.procedure_preset_fields FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at ON public.surgical_approaches;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.surgical_approaches FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at ON public.team_surgeons;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.team_surgeons FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at ON public.team_pas;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.team_pas FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at ON public.procedure_reexplorations;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.procedure_reexplorations FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at ON public.procedure_attachments;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.procedure_attachments FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at ON public.procedures;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.procedures FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at ON public.procedure_presets;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.procedure_presets FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();